#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'pio_clock_time', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CLOCK_TIME_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CLOCK_TIME_COMPONENT_TYPE altera_avalon_pio
#define PIO_CLOCK_TIME_COMPONENT_NAME pio_clock_time
#define PIO_CLOCK_TIME_BASE 0x0
#define PIO_CLOCK_TIME_SPAN 32
#define PIO_CLOCK_TIME_END 0x1f
#define PIO_CLOCK_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CLOCK_TIME_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_CLOCK_TIME_CAPTURE 0
#define PIO_CLOCK_TIME_DATA_WIDTH 32
#define PIO_CLOCK_TIME_DO_TEST_BENCH_WIRING 0
#define PIO_CLOCK_TIME_DRIVEN_SIM_VALUE 0
#define PIO_CLOCK_TIME_EDGE_TYPE NONE
#define PIO_CLOCK_TIME_FREQ 50000000
#define PIO_CLOCK_TIME_HAS_IN 1
#define PIO_CLOCK_TIME_HAS_OUT 0
#define PIO_CLOCK_TIME_HAS_TRI 0
#define PIO_CLOCK_TIME_IRQ_TYPE NONE
#define PIO_CLOCK_TIME_RESET_VALUE 0

/*
 * Macros for device 'pio_clock_mode', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CLOCK_MODE_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CLOCK_MODE_COMPONENT_TYPE altera_avalon_pio
#define PIO_CLOCK_MODE_COMPONENT_NAME pio_clock_mode
#define PIO_CLOCK_MODE_BASE 0x20
#define PIO_CLOCK_MODE_SPAN 32
#define PIO_CLOCK_MODE_END 0x3f
#define PIO_CLOCK_MODE_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CLOCK_MODE_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_CLOCK_MODE_CAPTURE 0
#define PIO_CLOCK_MODE_DATA_WIDTH 32
#define PIO_CLOCK_MODE_DO_TEST_BENCH_WIRING 0
#define PIO_CLOCK_MODE_DRIVEN_SIM_VALUE 0
#define PIO_CLOCK_MODE_EDGE_TYPE NONE
#define PIO_CLOCK_MODE_FREQ 50000000
#define PIO_CLOCK_MODE_HAS_IN 1
#define PIO_CLOCK_MODE_HAS_OUT 0
#define PIO_CLOCK_MODE_HAS_TRI 0
#define PIO_CLOCK_MODE_IRQ_TYPE NONE
#define PIO_CLOCK_MODE_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
